### ISSUE TITLE
Eraser icon position

### ISSUE THREAD

**Issue by Cacuu** [KnowZero/Krita-ShapesAndLayers-Plugin#1]
Hey, I love the plugin! been looking for something like this forever now.
I wonder if it's possible to add a distance for the icon to be offset from the center? That way I can use a more noticeable icon but not have it literally in the middle of my art.
Thanks!

**Comment by KnowZero** [comment]
You can set up your own icon and position in wherever. You just create a big icon and place a small image far away from the center.

Do note though that Krita has added their own eraser in Krita 5.1 by going to Settings->Configure Krita->General->Cursor and "Use separate settings for eraser". 

The plugin one still gives more flexibility though

**Comment by KnowZero** [comment]
Since a week has passed with no response I'll consider this issue solved.
